version: '2.1'

services:
  proxy:
    image: nginx:alpine
    hostname: ${NGINX_HOSTNAME:-localhost}
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - /etc/letsencrypt/live/naumachiactf.com:/etc/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .data/nginx/logs:/var/log/nginx
    networks:
      default:
      internal:
    depends_on:
      - ctfd

  ctfd:
    build: .
    restart: always
    expose:
      - "8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - LOG_FOLDER=/var/log/CTFd
      - USE_SSL=false
      - USE_RELOAD=false
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    env_file:
      - recaptcha.env
      - mysql_secrets.env
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTfd:ro
    depends_on:
      - db
    networks:
      internal:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true
